### ISSUE TITLE
Eufy Homebase Support

### ISSUE THREAD

**Issue by TbsJah** [ciddi89/ioBroker.device-watcher#73]
Would be great if also the cameras from Eufy could be added
All values are added with the adapter eusec 

![image](https://user-images.githubusercontent.com/34193151/204208087-cdcd03d0-bc20-4e10-b450-2d3f7f6c746b.png)
![image](https://user-images.githubusercontent.com/34193151/204208214-1a1fa76e-bec6-437e-8feb-1d4f6e41264c.png)
![image](https://user-images.githubusercontent.com/34193151/204208328-0fa0c125-536f-478f-8965-5f8c9853f302.png)
![image](https://user-images.githubusercontent.com/34193151/204208434-dac39afa-8b5f-481f-ab42-bb3abf146a70.png)

**Comment by ciddi89** [comment]
It is possible to give me the JSON of the folder construction? So it will be easier for me to get an image of the structure. With the screenshots it looks difficult to find out the correct affiliation because you did filtered it.
You can click on the eusec folder an download it with this circle red button:
<img width="469" alt="Screenshot 2022-11-28 at 20 55 28" src="https://user-images.githubusercontent.com/66088020/204368896-e112e63b-ce6b-4435-adec-b6bd9a4d0919.png">

thanks already

**Comment by TbsJah** [comment]
pls find attached
[eusec.json.txt](https://github.com/ciddi89/ioBroker.device-watcher/files/10109630/eusec.json.txt)

**Comment by ciddi89** [comment]
Hi @TbsJah 

Ich bin gerade dabei den Adapter mit einzupflegen. Brauch aber noch eine Info. Um die Geräte zu finden suche ich nach den Datenpunkt 'name' denn dieser scheint bei allen Geräten von euSec vorhanden zu sein. Aber wie oft aktualisiert dieser sich? (nicht stateChange, letzte Änderung! Sondern nur aktualisieren.) Um zu ermitteln ob ein Gerät noch online oder offline ist brauche ich am besten einen Datenpunkt der bei allen Geräten zu verfügung steht und der sich bei bestehender Verbindung regelmäßig aktualisiert.

Ich danke dir schon mal

**Comment by TbsJah** [comment]
Hallo @ciddi89
Der Datenpunkt *.software_version sollte immer verfügbar sein.
Eine Aktualisierung erfolgt nach dem eingegeben Intervall im Adapter
Standard sind 10 Minuten

**Comment by ciddi89** [comment]
okay Adapter ist mit drin. Kann entweder über die Github version getestet werden oder sonst warten bis zum nächsten release. Falls was nicht richtig funktionieren sollte einfach noch mal bescheid geben. :)
